/**
 * Letter Lock's two word lists.
 *
 * ANSWERS is the short one: every word the game will ever ask for. It was
 * written by hand for this arcade, and the bar is "a seven-year-old could
 * meet this word in a reading book". No swears, nothing rude, nothing about
 * fighting, drinking or smoking, no body parts, and nothing so obscure that
 * losing to it feels like a trick. The common words that British and American
 * English spell differently are left out too, so nobody loses a try to a
 * spelling argument. words.test.ts holds a blocklist against it.
 *
 * The daily word walks a fixed shuffle of ANSWERS (rules.ts), so changing this
 * list -- even adding to the end -- reshuffles every future day. That's fine
 * between releases, but two phones on different builds would then disagree
 * about today's word until both have updated.
 *
 * MORE_GUESSES is the long one: every other five-letter word a guess may be.
 * It is the public-domain ENABLE word list filtered to five letters, minus a
 * few dozen swears and slurs, so that typing one gets NOT IN THE LIST rather
 * than a row of tiles. It's packed: each chunk is a two-letter start followed
 * by every three-letter ending that goes with it, run together ("aahedliirgh"
 * is aahed, aalii, aargh). Sorted words share their first two letters so often
 * that this keeps 7,377 words to about 11 KB of the download, against 17 KB
 * written out in full.
 */

export const ANSWERS: readonly string[] = `
about above acorn actor admit adopt adore adult after again agent agree ahead
aisle alarm album alert alien alike alive alley allow alone along aloud amaze
amber among amuse angel angle angry apart apple apron arena argue arise aroma
arrow aside atlas attic audio avoid awake award aware awful bacon badge bagel
baker banjo basic basil basin batch baton beach beard beast began begin begun
being below bench berry bingo birch birth bison black blame blank blast blaze
blend bless blimp blind blink block bloom blown bluff blunt blurt blush board
boast bonus boost booth boots bored bossy bound brace braid brake brand brass
brave bread break breed brick bride brief bring brisk broad broke brook broom
broth brown brush buddy buggy bugle build built bulky bumpy bunch bunny burnt
burro burst bushy buyer cabin cable caddy cadet camel canal candy canoe cargo
carol carry carve catch cause cedar cello chain chair chalk champ chant chaos
charm chart chase cheap check cheer chess chest chewy chick chief child chili
chill chime chirp chive choir chomp chore chose chunk civil claim clamp clang
clank clasp class clean clear clerk click cliff climb cling cloak clock close
cloth cloud clove clown clump coach coast cobra cocoa comet comic comma coral
corny couch cough could count court cover craft crane crash crate crave crawl
crazy creak cream creek crepe crest crisp croak cross crowd crown crumb crush
crust cubic curly curry curve cycle daddy daily dairy daisy dance dandy dealt
decal decay decor delay delta denim dense depth derby diary digit diner dingo
dirty disco ditch diver dizzy dodge doing dolly donor donut doubt dough downy
dozen draft drain drake drama drank drape drawn dream dress dried drift drill
drink drive drone droop drove dryer dusty duvet dwell eager eagle early earth
easel eaten eater ebony eerie eight eject elder elect elite ember empty enemy
enjoy enter entry equal equip erase error erupt essay event every exact exist
extra fable fairy faith false fancy fault feast fence ferry fetch fever field
fiery fifth fifty final finch first fizzy fjord flake flame flare flash fleet
flick fling flint float flock flood floor floss flour flown fluff fluid fluke
flung flute flyer focus foggy force forge forth forty found frame freed fresh
fried frill front frost frown froze fruit fudge fully funny furry fussy fuzzy
gauge gecko geese genie genre ghost giant giddy given giver gizmo glade glare
glass glaze gleam glide glint globe gloom glory gloss glove gnome going golly
goody goofy goose gourd grace grade grain grand grant grape graph grasp grass
grate gravy graze great green greet grill grimy grind groan groom group grove
growl grown gruff grunt guard guava guess guest guide guild gummy guppy gusty
habit haiku handy happy hardy harsh haste hasty hatch haven hazel heard heart
heavy hedge hefty hello hence heron hiker hilly hinge hippo hitch hobby hoist
holly honey horse hotel hound house hover howdy huffy human humid hunch hurry
husky hutch hyena icing ideal igloo image index inner input issue itchy ivory
jazzy jeans jelly jewel jiffy joker jolly joust judge juice juicy jumbo jumpy
karma kayak kazoo khaki kiosk kitty knead kneel knelt knock known koala kooky
label large laser latch later latte laugh layer leafy leaky leapt learn lease
leash least leave ledge lefty legal lemon lemur level lever light lilac limbo
limit linen liner lingo llama lobby local lodge lofty logic loopy loose lotus
lower loyal lucky lumpy lunar lunch lyric macaw magic major maker mango manor
maple march marsh match mauve maybe mayor meant meaty medal media medic melon
mercy merge merit merry messy metal midst might mimic mince miner minor minty
minus mixer mocha model moist money month moody moose moral mossy motel motor
motto mound mount mouse mover movie mower muddy mulch mummy munch mural mushy
music musty nacho naive nanny needy never newly nicer niece nifty night ninja
ninth noble noise noisy nomad north notch noted novel nudge nurse nutty nylon
oasis occur ocean oddly offer often olive onion opera orbit order other otter
ought ounce outer owner ozone paint panda panel panic pants paper parka party
pasta paste patch patio pause peace peach pearl pecan pedal penny perch peril
perky pesky pesto petal petty phone photo piano picky piece piggy pilot pinch
pivot pixel pixie pizza place plaid plain plane plank plant plate plaza plead
pluck plume plump plush point polar polka pooch poppy porch pouch pound power
prank prawn press price pride prime print prism prize probe prong proof proud
prove prowl prune puffy pupil puppy purse pushy putty quack quail quake queen
query quest queue quick quiet quill quilt quirk quite quote racer radar radio
rainy raise rally ranch range rapid raven reach react ready realm rebel recap
refer regal reign relax relay renew reply reuse rhino rhyme rider ridge right
rinse ripen risky rival river roast robin robot rocky rodeo rogue roomy roost
rough round route rover rowdy royal rugby ruler rural rusty sadly saint salad
salon salsa salty sandy satin sauce scale scaly scamp scare scarf scary scene
scent scold scone scoop scoot scope score scout scowl scrap scrub serve setup
seven shack shade shady shake shall shape share shark sharp shawl sheep sheet
shelf shell shift shine shiny shirt shock shone shook shore short shout shown
showy shrub shrug sieve sight silky silly since siren sixth sixty skate skier
skill skirt skunk slack slang slant sleek sleep sleet slept slice slick slide
slime slimy sling slope slosh sloth slump slush small smart smell smile smirk
smock snack snail snake sneak sneer sniff snoop snore snort snowy soapy soggy
solar solid solve sonic sorry sound south space spade spare spark speak speck
speed spell spend spice spicy spied spike spill spoil spoke spoof spool spoon
sport spout spray squad squat squid stack staff stage stain stair stake stale
stalk stall stamp stand stare start state steak steam steel steep steer stern
stick stiff still sting stink stock stomp stone stony stood stool stoop store
stork storm story stove strap straw stray strum strut stuck study stuff stump
stung stunt style sugar suite sulky sunny super surge sushi swamp swarm sweep
sweet swell swept swift swing swirl swish swoop syrup table tacky taffy taken
tally talon tamer tango tangy tardy taste tasty teach teary teddy tempo tenth
thank theme there these thick thing think third thorn those three threw throw
thump tiara tidal tiger tight timer timid tired titan title toast today token
topaz topic torch total touch tough towel tower trace track trade trail train
trait trash tread treat trend trial tribe trick tried trike troll troop trout
truce truck truly trunk trust truth tulip tuner tunic turbo tutor twang tweak
tweet twice twine twirl twist tying ultra uncle uncut under union unite unity
unlit untie until unzip upper upset urban usher usual utter vague valid value
valve vault venue verse video villa vinyl viola viper viral visit visor vital
vivid vocal voice voter vowel wacky wafer wagon waltz watch water weary weave
wedge weigh weird whale wheat wheel where which while whine whirl whisk white
whole whose wider width windy wispy witch witty woman women woods woody wordy
world worry worse worst worth would woven wreck write wrong wrote yacht yeast
yield yodel young yours youth yucky yummy zebra zesty zippy
`
  .trim()
  .split(/\s+/);

const MORE_GUESSES = `
aahedliirgh
abacaaciackaftakaampaseashatebasbesbeyboteameleetshoridelerlesmhoodeohmoilomaoonortrisuseutsuzzyesysmyss
acarierbetahedheshooidsidyinginikeemesmicnednesockoldredresridtedtinuteyls
adageaptdaxdedderdleeemeptieuiositsmanmenmixobeoboornownozeuncustytazes
aeciadesgisonsrie
afarsfixireootoreoulrit
agamaapearsateaveazeeneersgergiegrohasileingiosismistleeletleylowmasoneonsonyorariaues
aholdull
aidedderdesledmedmeroliredrerrnsrthrtstchver
ajivauga
akeeselaene
alackamoandaneangansantaryatebascidderdolecsefsephfasgaegalgasgidgingorgumiasibiifsignineistiyakydkyllayleelodlotloylylmahmasmehmesmudmugoesoftohaoinoofphatarterthotosulaumsway
amahsainassbitblebosbryebaeerendensentiasiceiciideidoidsiesigaigoineinoinsirsissitymosnianicoksoleortourpleplypuluckyls
anconeareleentgasgergstileilsimaimeimiionisekhsklekuslasnalnasnexnoynuloasodeoleomysaetaetastedtestictistratretsyvil
aorta
apaceeakeekerseryhidhisianingishneaodsortpalpelplyressessistertly
aquaeuas
araksborcedcusdebdoreaeealeasecaeicetegalgilglegolgongotgushatiasielilslesmedmermetmoroidosepenrasrayrississontalteltsyumsvalvosyls
asanacotcusdichedhenheskedkerkewkoikospenperpicpissaisaysettertiryla
atapsaxyiltmanmasollomsomyoneonyopyriariptar
audadditgerghtgurlicntsntyraeralrarrasreiresricrisrumtosxin
availantastensersertgasianionisoows
awaitashingnedokeols
axelsialileilsingiomioniteledlesmanmenoneons
ayahsins
azansideidoinelonoicoleonsoteothure
baaedalsbasbelbesbkaboobulbusccacksddydlyffsffyggyhtsilsirnithitsizaizekedkeslasldsldyledlerleslkslkyllsllylmslmylsanalncondsndynednesngsnksnnsntyrberbsrderdsredrerresrfsrgericrksrkyrmsrmyrnsrnyronrreryesalsedsersessissksssissossysteststedtesthethstikttsttuttyudsulkwdswdywlswtyyedyouzarzoo
beadsadyaksakyamsamyanoansarsatsausautauxbopcapcksdeldewdimechefsefyepserseryetsfitfoggatgetgotgumigeigylaylchlgaliellellsllyltsmasmixndsndynesnnenninnyntsretrgsrmermsrthrylsetsomsotststastelthstonttavelvorwigzelzil
bhangootuts
bialialybbsblecesddydedderdesdeteldersffsffyfidghtglygotjoukedkerkeskielboleslgelgylksllsllymahmasmbonalndindsnesngenitntsomeontotapedpodrdsrksrlerlsrrsrsesesskstertestsyttsttyzes
blabsadeahsainamsandareaseateatsawnawseakeareatebseedeepentestetsimyiniipsissiteitzoatobsocsokeondoodoopotsowsowyubsuedueruesuetueyumeurbursype
boarsartatsbbycceccichecksdeddesffoffsgangeyggygieglegusheailsingitelarlasldslesllslosltslusmbembsndsnednesneyngongsnksnnennynzeobyoedogyoksomsomyonsorsotyozeozyralrasraxrerresricrneronrtsrtyrtzsksskysomsonsuntastchtelthyttsughuleurgurnuseusyutsvidwedwelwerwlswsexedxerxesyarylayoszos
brachactadsaesagsailainakyankansantashatsavaaviavoawlawnawsaxyaysazaazeeamedeeesensenteveewsiaribeieriesigsillimsineinkinsinyiositsittockoilomeomooncoodoososeosyowsughuinuitumeuntuskute
bubalbbyckocksdgeffiffoffsffyhlshrslbslgelgylksllallsllymfsmphmpsncondsndtngsnkonksnnsntsnyaoysranrasrbsrdsretrghrgsrinrkerlsrlyrnsrpsrrsrryrsarsesbysedsessksstsstytchteotlettettsttytuttylxom
bwana
bylawresrlsssitesway
cabalbbyberbobcaocaschectidesdgedgydisdreecafesffsgedgergesgeyhowidsinsirdirnjonkedkeskeylfsliflixlksllallslmslvelyxmasmeomesmpimpompsmpynednernesnidnnannynonnsonstntontsntypedperpesphsponposputratrborbsrdsredrerresretrexrksrlerlsrnsrnyrobromrpirpsrrsrsertertssassedsessksskystestssustertesttyuldulkulsvedvervesvievilwed
ceasebidcalcumdedderdesdisibailslebllallillslomltsnsentontsorlpesrciredresriaricrosstastites
chadsafeaffamsangapeapsaptardarearkarrarsaryasmatsawsayseateekeepefselaemoertethevyewsiaoiasicoicsideielileimbimpinaineinoinsipsirkirmiroirritsivyockokeokyoloookopsordottowsubsuckufauffugsumpumsurlurnurruteyleyme
ciboldergarliamexnchnesonsrcaresrriscossyststedtertesvetvicvievvy
clachackadeadsagsamsansapsaptaroaryashastaveaviawsayseateekefseftepeeptewsiftimeineinkipsiptodsogsombomponeonkonsootopsotsouroutoysozeubsuckueduesungunk
coactalaalsalyaptatiatsbbsbbybiablecasccicksckycosdasdecdeddenderdesdexdonedsffsgonhoghosifsignilsinsirskedkeslasldsledlesliclinllyloglonlorltslzamaemalmasmbembombsmermesmfymixmmympompsmptmtenchndonednesneyngangengonicninnksnkynnsntentonusochoedoeeoeroeyofsoksokyolsolyombopsoptotspalpedpenperpesprapserbyrdsredrerresrgiriarksrkyrmsrnsrnurpsrsesecsessetseysiestaststantedtesttaudeupeupsuthvedvenvesvetveyvinwedwerwlswryxaexalxedxesyedyerylyypuzenzeszeyzie
craalabsackagsakeampamsankapeapsassawsazeedoeedeeleepemeeptepyessewsibsickiedieriesimeimpipeociockocsoftoneonyookoonopsoreoupowsozeuckudeudsueluetumpuorurausewthypt
cubbybebbedberbesbitddyffsifsingishkeslchletlexllsllylmslpaltiltsminpelpidppappyrbsrchrdsrdyredrerresretrfsriarieriorlsrnsrrsrserstrvysecshysksspsssotchtertesteytietintisttytup
cyanoanscadcascloderlixmaemarmasmesmolnicstston
czars
daceschadasdosffsffyggahlslesllymanmarmesmnsmpsngsniorbsredrerresricrksrnsrtsshishytedtertestosttotumubeubsubyuntutsvenvitwedwenwkswnswtszedzes
deadsairalsansarsaryashathavebarbitbtsbugbutbyecafckscoscoycrydaledsedyemsepsersetsfatferfisfoggasgumiceifyignilsismistitykedkeskkoledleslfslftlisllsllylvemesmitmobmonmosmurnesntsoxypotratrayrmarmsrrysexskstertoxucevasvelvilvonwanwarwaxwedxesxie
dhaksalsobioleotiowsuti
dialsazocedcercesceyckycotctactydiedosdsteneetsghtkedkerkeskeyllsllymermesmlynarnednesngengsngynksnkyntsodeolsppypsorerrgerksrlsrtssciscsshyskssmetastestsyttottytzyvanvasvedvesvotvvywanxitzen
djinnins
doatsbbybieblabracksdgydosersestethffsgesgeyggoggygiegmailyitsjoslcelciledlesllslmalorltsmalmedmesmicnasneengangsnnannensyolyomsomyorsozypaspedperpespeyrksrkyrmsrmyrpsrrsrsartysedsersestaltedtertesttyuceumaumsurausevenveswdywedwelwerwiewnswrywsexieyenylyzedzerzes
drabsaffagsailamsatsaveawlawsayseadeareckeedeesegseksestibsieriesilyipsiptoitolloolopsoptossoukownubsugsuidumsunkupeuseyadyly
duadsalscalcatceschycksckyctsddydeddeselsetsffsitskedkesliallsllylsemasmbsmkamkymmympsmpynamncenchnesngsngynksntsomiomopedperpespleralrasredresrnsrocrosrrarrsrstrumsksskyststch
dwarfeebeltine
dyadsersingkedkeynelnes
eagreredrlsrnssedsesstsvedves
ebbedbetons
echedheshoslatrus
edemagedgergesictifyileitsuceuct
egadsersestgargedgerret
eiderdoskon
eking
elainandansatebowegyemifinideintoinopeudeuteverves
embarbaybedbowceeeerenderyeusirsitsmermetoteydeyds
enactatededderdowdueemanuiokiolsormowsrolskysuetiaurevoivoyzym
eosin
epacteeshahhashodhoricsochodeoxy
equid
erectgoticanesodeoseredsesuctugovil
escarcotkarkersestertop
etapeherhichoshylnasudeuisweeyma
euros
evadeensertictilsiteoke
ewers
exaltamscelecsertileineitsonspatpelpostoludeulturb
eyersingrasresrierir
facedcercescetciactsddydedderdesdgedosenaeryginilsintirskedkerkeskeykirllsmedmesnesngangsnnynonnosnumqirradrcercircyrdsredrerresrlerlsrmsrosrtsststaltedtestlytsottytwaughuldunaunsuvevasvesvorvuswnswnyxedxesyedzedzes
fearsaseatsazecalcescksedselsezeignintistlidllallsllylonltsmesmmemurndsnnyodsoffralresriarlyrmirnsrnyssetaltastedtestidtortusuarudsuedweryerylyzes
fiarsatsberbreceschechucincusdgedosefsendfedferfesghtlarlchledlerlesletllellollsllylmslmyloslthlumndsnednernesnisnksnnynosordqueredrerresrmsrnsrryrthscsshyststchtlyvervesxedxerxesxit
fjeld
flabsackagsailairakyamsamyankansapsaskatsawsawyaxyayseameaseckeereeseshewseysicsiedieriesipsirtiteitsocsoesogsongopsoraotaoutowsubsueduesukyumeumpunkuorushutyuytybyyte
foalsamsamycalehngeygiehnsilsinsistldslialiolkslkyllyndsnduntsodsolsotsotyramrayrbsrbyrdordsresrgorksrkyrmermsrtertsrumssasseulsuntursveawlsxedxesyer
fragsailancankapsassatsaudayseakeereesemdenaereetsiarieriesigsiseiskithitsittitzizzockoesogsondonsoreoshothowsugsumpyer
fubsycuselsgalggygiogleguegusjisllsmedmermesmetndindsngingonksnkyranrlsrorrzerzysedseeselsessilstytonzedzeezeszil
fyceskestte
gabbybleddididdisffeffsgedgergesilyinsitslahlaslaxlealesllsllylopmasmaymbambembsmedmermesmeymicminmmammympsmutnefnevngsnjanofolspedperpesppyrbsrnirthsesspsssyststedtestorudsudyultumsuntursussuzeuzyvelvotwkswkywpswsyyalyerylyzarzedzerzes
gearsckseksekyestldsleelidltsmmammymotnesnetnicniinipnoanomnrontsnuanusodeoidrahrmsrmyssosteststastupums
ghastatsautazieesoulyll
gibedberbesftsgasghegotgueldsllsllyltsmelmmempsmpynksnnyponpsyrdsrlsrlyrnsronrosrshrthrtssmostsves
glaceadsadyairandansaryazyeanebaebeedeedseedeekeeseetenseysialiasiffimeimsitzoamoatobsoggomsopsostoutowsozeuedueruesueyugsumeuonutsyph
gnarlarrarsashatsawnaws
goadsalsatsbanbosdetdlyersfergosldslemlfsmbonadnefnerngsnianifnofnzoodsoeyofsokyonsonyopsopyosyralredresrgerpsrsersyugeutsutywanwdswkswnsxesyim
graalabsadsaftailamaampamsanaansapyaveaysebeeedeekeesegoeysideidsiefiffiftigsimeinsiotipeipsiptipyistithitsoatogsoinopeossoszotsoutowsubsueluesumeump
guacoanoansarscksdesffsidsileiltiroiselaglarlchleslfslfyllsllylpslpymbommanksnkynnyrgerryrshrusshyssystoststsyttattyyedyot
gybedbespsyralredresronrosrusvedves
haafsarsbuscekcksdaldeddesdjidstemsetsfisfizftshasikaiksilsirsiryjesjisjjikeskimledlerleslidllollslmalmslosltslvalvemalmesmmymzancendsngsnksnkynsansentsolepaxplyrdsredremresrksrlsrmsrpsrpyrryrtsspstedtertesughulmulsuntutevervesvocwedwkswseyedyerzanzedzerzes
headsadyalsapsarsathatsavebescksderdgyedselsezeftsighilsirsistliolixllslmsloslotlpslvemalmesmicminmpsmpynnanryntsrbsrbyrdsresrlsrmarmsrnsrosrryrtzststhsuchughwedwerxadxedxerxesxyl
hicksdedderdesghsghtkedkeslarllollsltslumlusndsnnyntsppyredrerresssystsvedves
hoagyardarsarybosckscusdadersganggsickisekedkeskeykkukumldsledlesleylksllallolmsltsmedmermesmeynanndanednernesngsnksnorochodsodyoeyofsokaoksokyolyopsotsotypedperpesppyrahralrasrdernsrstrsysedselsensesstaststchtlyuriursvelweswffwfswkswlsyasyle
hubbycksffsgerlaslkslkyllollsmicmormphmpsmpymusnksnkyntsrdsrlsrlyrstrtssksssyzza
hydradroinglasmenmnsoidpedperpesphaposraxson
iambimbs
ichorierilykeronstictus
ideasiomiotledlerlesolsyllyls
iglus
ihram
ikatsons
ileacealeumeusiaciadialiumler
imagoamsaumbedbueideidoidsineinomixpedpelpisply
inaneaptarmbyecogcurcusdiedoldowdridueeptertferfixfosfraglegotionkedkerklelayletnedsettertistroureurnvar
iodicdiddinnictas
iradeateidsingkedokooneonsony
isbasledlesletseitle
itemsher
iviedies
ixiasoratle
izars
jabotcalcksckydeddesgerggsggygrailskeslaplopmbembsmmynesntypanpedperpesrlstosuksuntupsvaswanwed
jebelepsersfeshadhusllsmmynnyridrksrkyrrysseststestonttywed
jibbsbedberbesffshadllsltsmmympyngonksnninnssmsvedvervesvey
jnana
jockockseyshnsinsintistkedkeskeylesltsltynesramrumtasttyualuksulewarwedwlswlyyed
jubasbesdasdosgalgumjuskedkeslepmpsnconksnkyntantopesponralratrelrorststestty
kababbarbobdisfirgusiakifsilsinskaskislamlesliflpamesmiknasnesnjionspasphspokppaputratrnsroorstrtsshatasuriuryvasyos
kbars
kebabbarbobcksdgeefsekselsensepsetsevefirirsleplimllylpslpympsmptnafnchndonospisrbsrfsrnernsrrytchtolvelvilxesyed
khadiafsansaphatsedaethetsoum
kiangbbebbibeibesblacksckyddoddyefserslimllslnslosltsltynasndsnesngsninnksnkynosrksrnsssyststedtertesthethsvaswis
klongoofugeutz
knackapsarsauraveeedeesellifeishitsobsollopsospotsoutowsurlurs
koanselshlsinelaslosnksokspekphspjepparairatruntostow
kraalaftaitauteepillonaoneoonubi
kudosdusdzugelkrilakmysrtarussso
kvass
kyackaksarsatslixrietesthe
laaribiaborbracedcercesceycksdeddenderdesdleevogangerharichicsighirdirsithitykedkerkeskhsllsmasmbsmbymedmermesmiampsnaincendsnesnkypelpinpispserchrdsrdyreeresrgorisrksrkyrumrvasedsesssoststedtentexthethithsthytkeuanudsuravasvedverveswedwnswnyxerxlyyedyupzarzedzes
leachadsadyafsaksansantapsarsaryavybendgyechekserseryetsftsgergesggygithrshuamanmmandsnesnisnosnsentooneperptatchthetupudsveevinwisxesxiszzy
lianaaneangardarsbelberbrabrichichtcitcksdardosegeenserseuseveferftsgangerkedkenkerkesltsmanmasmbambimbsmbymedmenmesmeymnsmosmpampsnacndynednesneyngangsngyninnksnkynnsnosntsntynumonspidpinppyrasrotslespsststaitasterthethotrevedvenvervesvidvre
llano
loachadsafsamsamyansathbarbedbesboschsckscoscumcusdendesessftsgangesggygiagoigosinsllsllynerngengsobyoedoeyofaofsoieoksomsonsonyopsotspedperpesppyralranrdsresrisrryselsersesssytahtastictosttettoughuieuisupeupsursuryuseusyutsvatvedverveswedweswlywsexedxes
luausbescescidckscredesdicffaffsgedgergesllslusmenmpsnasnesnetngengingsnksntspinpusrchredrerresridrksstsstysusteatedtesxes
lweis
lyardartaseceaceeingmphnchressedsessinsisssatictta
maarsbescedcerceschechochsckscleconcrodamdlydrefiaficgesgmagotgushoeidsileillilsimsinsirsistizekarkeskoslarleslicllslmslmyltsltymasmbambomeymiemmammynasnednesngengynianicnlynnanosnsentanusquircsresrgeriarksrlsrlyrryrsertsrvysershyskssonssassessyststedtertesteythstinttettstzatzoudsulsundutsvenvievinviswedxesximxisyanyasyedyosystzedzerzes
mbira
meadsalsalyansanyatsccadiiedsetsinyldsleelicllsltsmosnadndsnsansentanusousowsrdererresrksrlerlssasshysicsnesontedtertesthstistretrowedwlszeszzo
miaouaowasmaulcascheckscracroddydgedisensffsffyggskedkeskralchlerleslialkslkyllellsloslpaltsltymedmeomermesnaenasncyndsnednesngynimnisnkenksnnyntsredresrexrksrkyrthrzasdosersessosssystsstytertestistrettsxedxesxupzen
moansatscksdaldemdesdusggygulhelhurilsirairejoskeslallarlasldsldylesllsllyltoltsmesmmammymusnadnasndendongonienksnosnteochodsoedolaolsonsonyorsoryotspedperpespeyraerasrayrelresrnsronrphrrorsertsseysksssosteststestetteythsthytifttettsuchuesuldulturnusyuthvedveswedxasxiezos
mucidcincksckycorcrocusdraffsftiggsggyhlyjiklctledlesleyllallsmmsmpsmusngonisonsrasredresrexridrksrkyrrarrerrsrryscasedsersessksskyssysthststchtedtertestonttszzy
mynahnasoidomaopeopyrrhsidthsthy
naansbesbisbobcredasdireviggyiadifsilsirakedledmedmermesnasncencypesppeppyrcorcsrdsresricrisrksrkysalstytaltchtesttyvalvarvelvesvvywab
neapsarsathatscksedsemsepsgusifsighistllymasonsrdsrdyrolrtsrtzrvervyststopttsttyuksumeumsvesvuswelwerwiewsywtsxus
ngwee
nicadcheckscoldaldeddesduseveghshilllsmbinesnnynonpasppyseisustertestidtontretrottyvalxedxesxiezam
nobbyblycksdalddydesduselsggshowilsilyirslosmasmenmesmoimosnasncenesnetnyloksokyonsosepalriarisrmssedsesseytaltertestumunsvaevaswaywts
nubbybiachaderdzhkedkesllsmbsmenrdsrlstsy
nyalamph
oakenkumredsesststenterthsves
obeahelieseeysiasitsjetoesoleoliols
ocherhrehrykerreatadtaltantettyluli
oddereoneumistiumorsouryleyls
ofaysfalfedter
ogamseeshamiveledlerlesres
ohiasingmic
oidialedlernks
okapiaysehsras
oldenderdieeiceineoseumioslasogy
omasaberbreegaensersits
oneryiumsettic
oohedmphrietidzedzes
opahsalsensineingiumsintedtic
orachalsangatebedcascindoseadgangicibiielleslopmernispinristhozos
osiermicmolsiatia
ottartos
ouphephsrieselststbytdotedtgotrezelzos
ovalsaryateensersertineoidolioloule
owingletnedsen
oxboweyeideidsimeimslipter
oyers
pacascedcerceschacksctsddydisdledredrieaneongangedgergesgodiksilsinsirsisaiselealedlerlesletllsllylmslmylpilpslsympandynednesngangsnnensyntontypalpaspawppippyrasrchrdirdsrdyredreorerresreurgergorisrksrlerolrrsrryrsertsrvervoseosesshassestsstytedtentertesthstintlytsyttyvanvedvervesvidvinviswedwerwkywlswnsxesyedyeeyeryor
peageagsaksakyalsansarsartaseatsatyavychscksckydesdroekselsensepserseryeveinsisekankeskinkoeleslfslonltsnalncendsnesngonnannennionsonyplaposppyrdurdyrearisrksrmsrryrsesosstsstytertitttittoweewit
phageaseialloxonoonsonyotsphtutsylayle
piansbalcalcasckscotculersetaetygmyingkaskedkerkeskislaflarlaulawlealedleileslisllslusmasmpsnasnednesneyngongsnkonksnkynnannynonnotntantontsnuponsouspalpedperpespetpitquernsrogscososstetastchthsthytonxes
plackageaitansashasmatsatyayaayseaseatebeebsenaewsicaiedieriesinkodsonkopsotsotzowsoysugsumbumsumyunkyer
poachcksckydgydiaemsesyetsgeyiluindisekedkerkeskeyledlerlesliolisllsloslyplysmesmmympsncendsnesngsodsofsofyohsolsonsopsoriovepesppapsyredresrgyrksrkyrnsrnyrtssedsersessitsseststsyttottyuffufsultursutsutyxedxesyou
praamahuamsangaosaseateatsausayseedeeneesepsesaeseestexyeysickicyiedieriesigsillimaimiimoimpimsinkionioriseissivyoasodsoemofsogsoleomoomsoneopsoseosoossostosyowsoxyudeutayer
psalmeudhawoaeoaioasych
pubiscesckacksdgydicffsggyjahjaskedkeskkaledlerlesliklisllslpslpylsemasmpsnasnchngsnkanksnkynnyntontsntypaepalpasrdareererrgerinrisrlsrrsrsysestonttittotts
pygmyinslonoidranresricxesxiexis
qaidsnat
qophs
quadsaffagsaisakyalealmantarearkartashasiassateayseaneerellerneysidsiffinsintipsipuireirtitsodsoinoitotaothrsh
rabatbbibicbidcedcesckscondiidixdonffsftsgasgedgeegesggygisiasidsilsinsjahjasjeskedkeekerkeskisleslphmeemetmiemmympsmusncendsndyneengynidnisnksntsperpheredrerressedsersesspsspytaltantchtedteltertesthetiotosttyvedvelvervesvinwerwinwlyxedxesyahyasyedyonzedzeezerzeszor
readdadsalsamsapsarmarsataavebarbbebecbidbopbusbutbuyccecksconctactictocurcutdanddsdeddesdiadiddipdlydondosdoxdrydubduxdyeedsedyefsefyeksekyelsestevefedfelfitfixflyfrygesgmagnahabhemifsifyinkinsivekeyletliclitmanmapmetmexmitmixnalndsnigninntentsoilpaypegpelpinpospotppsproranrigrunsawsayseesetsewsidsinsodsowststagtaxtchtemtiatietrotryvelvetvuewanwaxwedwetwinwonxes
rheaseumombumbyta
rialsantatabbybescedcercescincksdesdgyelsferffsfleftsgidgorledlesleyllellsmedmermesndsngsnksojaotspedperpessensersesshiskssustestzyvedvenvesvetyal
roachadsamsansarsbedbesblecksgerilsilyleslfsllsmanmeompsndoodsofsoksokyomsoseotsotypedperpespeyquesedsessetsintastchtestistlstortostteuenuesugeupsupyuseustuthutsvedvenveswanwedwelwenwerwth
ruanabesblebuschecksddsddyderersffeffsgaegalinginsledlesmbamenmmymormpsnesngsnicnnyntsntypeesesshysksststhstintty
rykedkesndsots
sabedberbesbinbirblebotbrabreckscradesdhedhudisferfesgasgergesggygosgumhibiceidsigailsinsithjoukerkeskislallepleslicllylmilollpalpsltslvelvombambomekmpsndsnednernesnganghntopidporppyranrdsreergerinrisrksrkyrodrossinssytaytedtemtestistyruchucyughulsultunauryutevedvervesvinvorvoyvvywedwerxesyeryidyst
scabsadsagsaldallalpamsansantapearparsartatsattaupaurenaendhavhmohulhwaionoffopsornotsourowsragramreerewrimriprodrumubaudiudoudsuffulkullulpumsupsurfutauteuts
sealsamsamyarsatsbumccoctsdanderdgedgydumedsedyekselselyemsepsepyersgnignogosgueifsineiseismizelahlfsllellslvamesmisndsnginnanornsansententipalpiapicpoyptaptsracrairalredrerresrfsrgerifrinrowrryrumrvotaetaltonttsverwanwarwedwerxedxesxtoxts
shadsaftagsahsakoakyalealtalyameamsankardarnaulaveawmawnawsayseafealeareasedseeneereikendenteolerdewnewsiedielieriesillilyimsinsipsireirkirristivaiveivslepoaloatoedoeroesogsojiooloonoosootopsorlornoteotsottoveowsoyuredrewristikuckulnulsunsuntushuteutsyeryly
sialsbbsbylcesckocksdeddesdleegeeurftsghsgilgmagnskerkesldslexlksllslosltsltylvamarmasmpsnesnewngengsnhsnksnuspedpesredreeresrrarupsalsesssytartedtestuptusverxesxmoxtezarzedzerzes
skagsaldatseaneedeeneeseetegseinelmelpeneepsewsidsiediesieyiffimoimpimsinkinsintipsirlirriteitsiveoaloshuasulkullyedyey
slabsagsainakeamsankapsashateatsatyaveawsaysedsewsierilyimsinkipeipsiptitsobsoesogsoidojdoopopsotsowsoydubsueduesuffugsumsungunkurburpursyerylyype
smackaltarmashazeeareekelterkewsiteithogsokeokyoltoteuts
snafuagsakyapsarearkarlashathawseapeckedsellibsickideipeipsitsobsogsoodookooloototsoutowsubsuckuffugsyes
soaksapsarsaveberckockscledasddydicdomfarfasftaftsftyilsjaskeskollanldildoledleileslonloslumlusmasnarndenesngsnlynnynsyoeyoksothotsotyphsphyporppyrasrbsrdsrelrerresrgornsrtsrusthstolughuksulsupsupyursusewarwedweryasyuzzin
spacyadoaedaesahiailaitakealeallangankansarsasmateatsawnayseanearecseeleereileireltentermewsicaickielieriesiffiksikyileiltineinsinyireirtiryiteitsitzivslatlaylitodeookoororeotsragratreerigritruerugudsueduesumeumyunkurnursurtuta
squabuawueguib
stabsadeagsagyaidaiganeangankapharkarsashatsaveayseadealeedeekeinelaeleemsenoepsereetsewsichiediesileiltimeimyintipeirkirpirsoaeoaioasoatobsogyoicokeoleomaookopeopsoptossoupouroutowpowsreprewriariproprowroyubsudsullumsunkunsupaupeurtyedyesyliymy
suavebahbasberckscreddsdordsyedeersetsetyghsingintitslcilfalfolksllylusmacmmamosmpsnnannsnuppesprarahralrasrdsrerrfsrfyrgyrlyrratratta
swabsageagsailainaleamiamyangankansapsardarearfartashathatsayseareatedeeerigsillimsineinkipeissithiveobsoonopsordoreornotsounung
syceeceskeslislphlvanchncsnodnthphsrensop
tabbyberbesbidblabooborbunbuscescetchechscitckscosctselsfiahrsigailsinsintjeskerkeskinlarlaslcslerleslkslkyluklusmalmedmesmismmympsngsnkanksnsyntopaspedperpespirpisrdoredresrgernsrocrokrosrotrpsrrerryrsirtsrtysksssetartertesttyuntupeutswedwerwiewnywsexedxerxesxisxonxuszzazze
teaksalsamsarsaseatschyctaelsemsensenyethffsguaiidindlaeleslexlialicllsllyloilosmpimpsmptnchndsnetnianonnornsentsntypalpaspeepidpoyraircergarmsrnernsrrarryrseslastastsstythstrauchughwedxasxts
thackanearmawsebeecaeftegneineirensermetaewsewyiefighillineinsiolirloleongoroorpousrawriprobroerumudsugsujaumbunkurluyaymeymiymy
tibiacalcksdeddesersffsgonkeskislakldeledlerlesllslthltsmedmesnctneanednesngengsnnyntspisppypsyresrlsrosterthetistrezzy
toadsadyddyffsffyftsfusgaegasgueileilsitskaykedkerkeslanlasledlesllsluslylmanmbsmesmmynalndindonednernesneyngangsnicnnenusolsonsothotspedpeeperpesphephiphspispoiposquerahrasrcsresricriirosrotrsersirskrsortertsrustedtemtertesursuseutswedwiewnswnyxicxinyedyeryonyos
tractagiaikampamsankanqansapsaptassaveawlayseedeeneeseksessetsewseysiaciadiceieriesigoigsillimsineioliosipeipsiteoakockodeoisokeomponaoneoozopeothotsoveowsoysuedueruesugsullumpussymayst
tsadeadiarskeduba
tubaebalbasbbybedberbescksfasffsftsftylesllemidmmymormpsnasnednesngsnnypikquerfsrfyrksrnsrpsshysksteettittytusxesyer
twaesaineedeenerpierigsillinsinyirpitsixtyer
tyeeserskesnednespalpedpespeypicposppsredresrosthe
tzars
udder
uhlan
ukase
ulamaansceremanadnaenarnaspanvas
umbelberbosbraiaciakiaqped
unaisaptarmaryausbanbarbidboxcapciacoscoycusdeedidduefedfitfixgothathipifyitslayledletmanmetmewmixpegpenpinrigripsaysetsewsexwedwitwon
upbowbyedosdryendlitped
uraeiareariaseatebiaealeasedoeicgedgergesialinesae
usageersingneaqueurpury
uteriile
uvealeasula
vacuagalgusilsirskillesletlorlsempsndanednesngspidporrasriarixrnarusrvesalsesstsstytictusunt
vealsalyenaepserserygangieilsinsinylarldsldtlumnaenalndsngeninnomntsrbsrgersorstrtsrturvestaststchxedxerxesxil
vialsandbescarcedceschyersewsewygasgilgorlerllillsmennalnasncanednesnicnosolsreoresrgaridrlsrturussassedsesstataettavasxenzirzor
vocesdkadungiegueidsilailelarledlesltalteltiltslvamermittedtesuchwedwer
vroomouwows
vuggsggyghslgo
vying
wackeckocksddydedderdesdisffsftsgedgergeshooifsilsinsirsistitsivekedkenkerkesledlerleslksllallsllymesmusndsnednesneynlyntsrdsredresrksrmsrnsrpsrtsrtyshyspsspysteststapttsughuksulsvedvervesveywlsxedxenxerxes
wealdalsansarsbbyberchtdeldgyedsedyeksensenyepsepyestetsftsirskaslchldsllsllylshltsnchndsnnyststly
whackamoamsangapsarfatsaupealeeneepelkelmelpensetsewseysidsiffigsimsinsinyipsiptirrirsishistitsityizzompoofoopopsorlortosoump
wicksddydendesdoweldfedfesftyganggyghtlcoldsledlesllsllyltsmpsmpyncenchndsnednesneyngsngynksnosnzepedperpesredrerresrrasedsersesshaspsststantedtesthethyvedverveszenzes
woadsalddgefulkenldslfsmbsmbynksnkyntsoedoerofsolsolyopsoshozyrdsrksrmsrmyrtsundwed
wrackangapsaptatheakensestickiedieriesingistitsothungyeryly
wurstssy
wyledlesndsnnstedtes
xebecnianicnonricroxrus
xylanlemlollylstists
yacksffsgergishooirdmenmunngsnkspokponrdsrerrnsudsuldupswedwlswnswps
yeansarnarscchchschyggslksllslpsntanterbarkssestisttsuksuky
yikesllsncepesrdsrrsrth
ylems
yobbocksdhsdlegasgeeghsgicgingiskedkelkeslkslkymimnicnisresurnusewedweswiewls
yuanscasccacchcksgaslanlesponrtarts
zairemianzappyrfsxesyinzen
zealsbecbusinsrksrosststas
zibetlchllsncsncynebngsngynkyramtiszit
zloteoty
zoeaeealeasmbinalnednernesnksoidoksomsonsotyrilriswie
zymes
`;

function unpack(packed: string): string[] {
  const words: string[] = [];
  for (const chunk of packed.trim().split(/\s+/)) {
    const start = chunk.slice(0, 2);
    for (let i = 2; i < chunk.length; i += 3) words.push(start + chunk.slice(i, i + 3));
  }
  return words;
}

/** Every word a guess may be: the answers, plus the long list. */
export const ALLOWED: ReadonlySet<string> = new Set([...ANSWERS, ...unpack(MORE_GUESSES)]);

/** True for a real five-letter word, in lower case. */
export function isAllowedGuess(word: string): boolean {
  return ALLOWED.has(word);
}
